name: Bug Fix
description: Fixed a bug? This is the way to submit it!
labels:
  - "priority: p4 not applicable"
  - "status: acknowledged"
  - "type: bug"

body:
  - type: markdown
    attributes: 
      value: |
        Thanks for fixing a bug!
        Ill be personally checking this bug fix and merging it as soon as possible.
  - type: input
    validations:
      required: true
    attributes:
      label: What bug does this patch fixes?
      description: Please enter a pound/hashtag character and the number of the bug report.
      placeholder: Something like \#12.
  - type: textarea
    validations:
      required: true
    attributes: 
      label: What does this fix accomplishes?
      placeholder: For example, "This fixes the problem in \#12 by adding a check in File.cs".
  - type: textarea
    attributes: 
      label: Anything else you might want to add?
      placeholder: All information is welcome here!
