blank_issues_enabled: false

contact_links:
  - name: General Questions
    url: https://discord.gg/Cf6sspj
    about: Do you have any questions about using this mod/library? Join the Discord server!
