name: Update Labels
on:
  push:
    paths:
      - labels.yml
      - .github/workflows/labels.yml
  schedule:
    - cron: "11 13 * * 3"
  workflow_dispatch:

jobs: 
  update:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4.1.7
      - uses: actions/setup-python@v5.0.0
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt
      - run: python labels.py
        env:
          LEMON_TOKEN: ${{ secrets.LEMON_TOKEN }}
          LEMONUI_TOKEN: ${{ secrets.LEMONUI_TOKEN }}
